title: "Make government better, **together**."
description: "Moving from open government to collaborative government"

exclude:
  - script
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - readme.md
  - node_modules
  - ".sass-cache"
  - "package.json"
  - "*.scss"
  - "*.coffee"
pygments: true
markdown: kramdown
